name: OTCv8 Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
          vcpkgGitCommitId: 3b3bd424827a1f7f4813216f6b32b6c61e386b2e
          runVcpkgFormatString: >
            install --triplet x86-windows-static
            boost-iostreams boost-asio boost-beast boost-system boost-variant boost-lockfree boost-process boost-program-options boost-uuid boost-filesystem
            luajit glew physfs openal-soft libogg libvorbis zlib libzip bzip2 openssl

      - name: Build
        run: msbuild /p:Configuration=Release /p:Platform=Win32 otclient.sln

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: otc-windows
          path: bin/Release/otclient.exe

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libglu1-mesa-dev pkg-config libphysfs-dev libopenal-dev libogg-dev libvorbis-dev zlib1g-dev libzip-dev libbz2-dev libssl-dev

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
          vcpkgGitCommitId: 3b3bd424827a1f7f4813216f6b32b6c61e386b2e
          runVcpkgFormatString: >
            install --triplet x64-linux
            boost-iostreams boost-asio boost-beast boost-system boost-variant boost-lockfree boost-process boost-program-options boost-uuid boost-filesystem
            luajit glew physfs openal-soft libogg libvorbis zlib libzip bzip2 openssl

      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: otc-linux
          path: build/otclient

  build-android:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Android SDK and NDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 30
          ndk: 23.1.7779620

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
          vcpkgGitCommitId: 3b3bd424827a1f7f4813216f6b32b6c61e386b2e
          runVcpkgFormatString: >
            install --triplet arm64-android
            boost-iostreams boost-asio boost-beast boost-system boost-variant boost-lockfree boost-process boost-program-options boost-uuid boost-filesystem
            luajit glew physfs openal-soft libogg libvorbis zlib libzip bzip2 openssl

      - name: Build
        run: |
          cmake -B build-android \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build-android --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: otc-android
          path: build-android/**/*.so
